Repository microbiomedata/nmdc-field-notes, pull requests merged in 2024-02, with the labels that each got.

#21 Implement `404.html` page that redirects to domain root
  public/404.html
Labels: x small, web-app :earth_americas:

#25 Replace boilerplate app name with real one
  index.html
  public/manifest.json
Labels: x small, cleanup :broom:, web-app :earth_americas:

#26 Authenticate with nmdc-server backend
  .env.local.example
  .env.staging
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  src/App.tsx
  src/QueryClientProvider.tsx
  src/Router.tsx
  src/Store.test.tsx
  src/Store.tsx
  src/api.test.ts
  src/api.ts
  src/components/AuthRoute/AuthRoute.tsx
  src/mocks/server.ts
  src/pages/Home.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LogoutPage/LogoutPage.tsx
  src/pages/TokenPage/TokenPage.tsx
  src/pages/WelcomePage/WelcomePage.tsx
  src/queries.test.tsx
  src/queries.ts
Labels: enhancement

#31 Support deep linking on GitHub Pages
  index.html
  public/404.html
  src/Router.tsx
Labels: bug, x small, web-app :earth_americas:

#39 Create universal link-related files in `public` folder
  public/.well-known/README.md
  public/.well-known/apple-app-site-association
  public/.well-known/assetlinks.json
Labels: enhancement, x small, ios-app :apple:, android-app :robot:

#38 Implement tab-based navigation
  src/Router.tsx
  src/components/StudyList/StudyList.tsx
  src/components/TabNavigator/TabNavigator.tsx
  src/pages/PlaceholderPage.tsx
Labels: enhancement
